[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl", "python3", "gnumake", "gcc"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = [
  "cd backend && npm run db:generate",
  "cd backend && npx prisma migrate deploy"
]

[start]
cmd = "cd backend && npm run start"

